// <auto-generated />
namespace PRSProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class switchedtheJsonIgnoreattributebacktocorrectspot : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(switchedtheJsonIgnoreattributebacktocorrectspot));
        
        string IMigrationMetadata.Id
        {
            get { return "201803131651552_switched the JsonIgnore attribute back to correct spot"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
